version: '2'

services:
  admin-server:
    image: service-admin-server:latest
    container_name: admin-server
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize", "-wait=tcp://discovery-server:8761", "-timeout=60s", "--", "java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseContainerSupport", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]
    ports:
      - 9090:9090
